### ISSUE TITLE
请问你的限价下单接口调通了吗？

### ISSUE THREAD

**Issue by WanderZY** [archerfeel/homebrew-trader#1]
Java post数据过去，side type等参数，是置于body里面过去吗，但是我请求过去是400。请问有遇到过吗？

**Comment by archerfeel** [comment]
可以正常下单啊，参见 https://github.com/archerfeel/homebrew-trader/blob/master/trader-fcoin-sdk/src/main/java/xyz/homebrew/sdk/fcoin/FCoinAccount.java#L198
